// Generated by CoffeeScript 1.6.3
var count, promise, request;

promise = require('when');

request = require('request');

count = function(user) {
  var api, deferred, fetch, getUrl, process;
  api = 'http://api.metacpan.org/v0/author/:user?join=release&q=release.status:latest';
  deferred = promise.defer();
  getUrl = function(user) {
    if (user == null) {
      user = '';
    }
    return api.replace(':user', user);
  };
  fetch = function() {
    var url;
    url = getUrl(user);
    return request({
      uri: url
    }, process);
  };
  process = function(error, res, body) {
    var cpan;
    if (error || body.charAt(0) !== '{') {
      return deferred.reject(error || body);
    } else {
      cpan = JSON.parse(body);
      if (cpan.code && cpan.code === 404) {
        return deferred.reject(cpan.message);
      } else {
        count = cpan.release.hits.total || 0;
        return deferred.resolve(count);
      }
    }
  };
  fetch();
  return deferred.promise;
};

module.exports = count;
